# Generated by Django 4.1.5 on 2023-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetbalancechange",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "INCOME"), ("EXPENSE", "EXPENSE")], max_length=16
            ),
        ),
    ]
