# Generated by Django 4.1.5 on 2023-01-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_alter_budgetbalancechange_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetbalancechange",
            name="category",
            field=models.CharField(
                choices=[
                    ("OTHER", "OTHER"),
                    ("GROCERY", "GROCERY"),
                    ("TAXES", "TAXES"),
                ],
                default="OTHER",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
