# Generated by Django 4.1.5 on 2023-01-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_alter_budget_members_alter_budget_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.TextField(),
        ),
    ]
